# Generated by Django 4.2.2 on 2023-06-20 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=150, verbose_name='Descrição')),
                ('cpf', models.IntegerField(verbose_name='CPF')),
                ('vinculo', models.CharField(max_length=12, verbose_name='Vínculo')),
                ('armario', models.IntegerField(verbose_name='Armário')),
                ('gaveta', models.IntegerField(verbose_name='Gaveta')),
                ('situacao', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setor', models.CharField(max_length=15, verbose_name='Setor')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.funcionario')),
            ],
        ),
    ]
