# Generated by Django 4.2.2 on 2023-06-21 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.IntegerField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(max_length=6, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='situacao',
            field=models.BooleanField(default=True, help_text='Marcado para Ativo. '),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='vinculo',
            field=models.CharField(choices=[('C', 'Comissionado'), ('CO', 'Contratado'), ('CN', 'Concursado')], max_length=12, verbose_name='Vínculo'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
